# the chart will iter on apps
apps:

    # here is what a very simple app can look like:
  - name: simple-echo
    image: traefik/whoami@sha256:200689790a0a0ea48ca45992e0450bc26ccab5307375b41c84dfc4f2475937ab
    service: 80
    ingress:
      domain: echo.domain.com


    # here is a more complex deployment with various available options
    # name for the deployment and pods
  - name: busy
  
    # image  
    image: busybox@sha256:37f7b378a29ceb4c551b1b5582e27747b855bbfaa73fa11914fe0df028dc581f

    # use this key to configure the deployment
    deploymentSpec:
      strategy:
        type: Recreate

    # env vars
    env:
      - name: key
        value: val

    # classic volume definition
    volumeMounts:
      - name: config
        mountPath: /etc/app
      - name: data
        mountPath: /data
    volumes:
      - name: config
        configMap:
          name: conf
      - name: data
        persistentVolumeClaim:
          claimName: data

    # extras spec for the pod
    extras:
      envFrom:
        - secretRef:
            name: test-secret

    # create a svc on that target port
    service: 8080
    
    # enable an anubis sidecar that will prxy the traffic to the pod
    anubis: true
    
    # will create a pvc w/ this name
    pvc:
      - data
    
    # create the appropriate ingress
    # default ingressclass is traefik, traefik-tunnel if public: true
    ingress:
      public: true # default to false
      domain: app.domain.com


# shortcuts for creating simple configmaps
configmaps:
  conf:
    key: value
